# Generated by Django 4.2.6 on 2023-11-14 11:54

import storages.backends.s3
from django.db import migrations, models

import user_management.models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=user_management.models.upload_to,
            ),
        ),
    ]
