services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    command: ["./entrypoint.sh"]
    volumes:
      - .:/code
    ports:
      - ${WEB_PORT}
    env_file:
      - .env
    depends_on:
      - db
