version: '3'
services:
  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRE_SQL_PORT}
  web:
    build: .
    command: ["./entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - ${WEB_PORT}
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery-worker:
    build: .
    command: ["./celery-worker.sh"]
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: ["./celery-beat.sh"]
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
