version: "3"
services:
  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRE_SQL_PORT}
  web:
    container_name: web
    build: .
    command: ["./entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - ${WEB_PORT}
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}
  celery-worker:
    build: .
    restart: always
    command: ["./celery-worker.sh"]
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    restart: always
    command: ["./celery-beat.sh"]
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis
  localstack:
    container_name: aws-localstack
    image: localstack/localstack:latest
    restart: always
    hostname: localstack
    ports:
      - ${LOCALSTACK_PORTS}
    env_file:
      - .env
    volumes:
      - ./aws:/etc/localstack/init/ready.d
      - "/var/run/docker.sock:/var/run/docker.sock"
