# Generated by Django 4.2.6 on 2023-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                blank=True, choices=[("short", "Short"), ("long", "Long")], max_length=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price_limit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
