# Generated by Django 4.2.6 on 2023-10-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_order_type_alter_order_price_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user_action_type",
            field=models.CharField(
                choices=[("buy", "Buy"), ("sell", "Sell")], default="buy", max_length=4
            ),
            preserve_default=False,
        ),
    ]
