# Generated by Django 4.2.6 on 2023-10-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_user_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="closing_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
