# Generated by Django 4.2.6 on 2023-11-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="available_quantity",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
