# Generated by Django 4.2.6 on 2023-11-13 15:19

import storages.backends.s3
from django.db import migrations, models

import stocks.models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_stock_available_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storages.backends.s3.S3Storage(),
                upload_to=stocks.models.upload_to,
            ),
        ),
    ]
